### ISSUE TITLE
Mako Error General Setting

### ISSUE THREAD

**Issue by Maltoh** [pymedusa/medusa.github.io#121]
Hi

I was using Sickrage but came upon this very error and I couldn't get it to work after reinstalling multiple times python and sickrage so I thought moving to Medusa would work but, exact same error, any ideas ?

File C:\Python27\lib\encodings\utf_8.py:16, in decode:
return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe9 in position 5: invalid continuation byte

Branch: master Commit: f5973b28465246e67465d7d86bdc8aa74d13e659
Version: Unknown 
Database: 44.11

Python Version: | 2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:22:17) [MSC v.1500 32 bit (Intel)]
SSL Version: | OpenSSL 1.0.2o 27 Mar 2018
OS: | Windows-10-10.0.17134
Locale: | fr_FR.cp65001

**Comment by medariox** [comment]
Please open this issue on the correct issue tracker: https://github.com/pymedusa/Medusa/issues/new/choose
Also, make sure to include the full debug log and not just the error message otherwise we won't be able to help you.
