### ISSUE TITLE
Adding Exsisting Shows

### ISSUE THREAD

**Issue by amandalfrench** [pymedusa/medusa.github.io#133]
I am attempting to add shows that have specials. Medusa freezes and won't add the rest of the show

**Comment by p0psicles** [comment]
Fixed in develop branch

**Comment by amandalfrench** [comment]
how do i update to develop branch

**Comment by p0psicles** [comment]
You can do from settings - general

**Comment by p0psicles** [comment]
Or use git checkout -t origin/develop
