### ISSUE TITLE
Restore from Sickrage Backup

### ISSUE THREAD

**Issue by amandalfrench** [pymedusa/medusa.github.io#134]
Can I restore media from a sickrage backup

**Comment by amandalfrench** [comment]
When i attempt to restore, i get this error "CHECKVERSION :: [8803383] git config remote.origin.pushurl https://github.com/pymedusa/Medusa returned : error: could not lock config file .git/config: Permission denied. Treat as error for now"

**Comment by p0psicles** [comment]
Probably rights issue. Check usename/group on your `.git` folder

**Comment by p0psicles** [comment]
Next time use this for issues: https://github.com/pymedusa/Medusa/issues

**Comment by p0psicles** [comment]
Im not sure if that will work. Better do a new install. Then move over config.ini and the main, failed and cache.db. Then start.

**Comment by amandalfrench** [comment]
That worked. Thank you very much
