### ISSUE TITLE
error

### ISSUE THREAD

**Issue by jxer** [pymedusa/medusa.github.io#17]
this is new

Thread-15 :: [daf5388] Missing time zone for network: #0

**Comment by labrys** [comment]
@jxer Full-update any series that show a network of `#0`.  If it still shows `#0` after a full update, make sure that the show actually has a network listed on TVDB.

**Comment by jxer** [comment]
is there a way to find this without going through each show?

**Comment by medariox** [comment]
Please open an issue at https://github.com/pymedusa/Medusa if the issue persists.
