### ISSUE TITLE
Cars (Europe) (Sv,No,Da,Fi): Screen Issues

### ISSUE THREAD

**Issue by sehunoh2005** [pymedusa/medusa.github.io#173]
Medusa DS Emulator

**Comment by sehunoh2005** [comment]
![Screen Shot 2019-08-16 at 4 08 59 PM](https://user-images.githubusercontent.com/53791478/63196155-9a437f00-c042-11e9-86ff-f2d9e0e191e0.png)

**Comment by sehunoh2005** [comment]
Go to DeSmuME OR MelonDS to fix the screen issues.

**Comment by medariox** [comment]
What? Wrong repo.
