### ISSUE TITLE
Disney Planes (Europe) (En,Sv,Fi): Boost blocking issues

### ISSUE THREAD

**Issue by sehunoh2005** [pymedusa/medusa.github.io#174]
![Screen Shot 2019-08-16 at 4 08 25 PM](https://user-images.githubusercontent.com/53791478/63196338-08884180-c043-11e9-9525-3382bac22e85.png)

**Comment by sehunoh2005** [comment]
Go to DeSmuME OR MelonDS to fix this blocking issue.

**Comment by medariox** [comment]
Wrong repo.
