### ISSUE TITLE
Feature Request: Page Selection to Top of Shows Table.

### ISSUE THREAD

**Issue by DrakeJones** [pymedusa/medusa.github.io#194]
It would be nice to have the new Page Selection option at the top of Shows Table as well as the bottom of the page rather than having to scroll down to bottom of the page to advance.  A nice feature for any page with Page Selection option really.   Just to the left of  Select Columns drop down would be good.

**Comment by medariox** [comment]
This should be openen in the project repository: https://github.com/pymedusa/Medusa

**Comment by DrakeJones** [comment]
Done.
