### ISSUE TITLE
Trakt User custom list

### ISSUE THREAD

**Issue by sakulsol** [pymedusa/medusa.github.io#228]
Are you planning to implement the user custom trakt lists?

**Comment by p0psicles** [comment]
Yes

**Comment by sakulsol** [comment]
Thanks....

**Comment by p0psicles** [comment]
Next time please raise issues in: https://github.com/pymedusa/Medusa/Issues.
Your request will be implemented after this PR has been finished: https://github.com/pymedusa/Medusa/pull/5782
