### ISSUE TITLE
Can't sync schedule to calendar

### ISSUE THREAD

**Issue by jandreaucodes** [pymedusa/medusa.github.io#253]
I'm trying to use the "Subscribe" button on the Schedule to add it to my Calendar.

It opens Calendar (mac OS) but throws an error:

![image](https://user-images.githubusercontent.com/12860371/93210457-a316f080-f72d-11ea-8144-531d4dfd198c.png)

If I change the URL it's feeding from to my machine's IP address, it also fails.
If I change the URL it's feeding from to my public domain, it also fails, though it takes much longer to fail.

**Comment by medariox** [comment]
The issue tracker is here: https://github.com/pymedusa/Medusa/issues
