### ISSUE TITLE
Series title detection is wrong

### ISSUE THREAD

**Issue by doodyd** [pymedusa/medusa.github.io#385]
I suspect this error occurs when one series name is a prefix to another series.  In my case the series in question are "9-1-1" and "9-1-1: Lone Star".

Post processing for the series with the suffix (9-1-1: Lone Star) are failing. I have yet to prove it, but suspect the same is true for searches as I need to manually download this series.

Evidence:

Log entry: Missed file: /media/torrents/9-1-1.Lone.Star.S03E17.480p.x264-mSD[eztv.re].mkv: Processing failed: File exists. Marking it unsafe to replace. Reason: New quality is equal to current Allowed. Ignoring quality

The episode in question does not exist in my library.  The corresponding episode for 9-1-1 does exist.

Running this file name through the Guessit test produces the following:
{
    "title": "9-1-1",
    "episode_title": "Lone Star",
    "season": 3,
    "episode": 17,
    "screen_size": "480p",
    "video_codec": "H.264",
    "video_encoder": "x264",
    "release_group": "mSD",
    "container": "mkv",
    "type": "episode",
    "parsing_time": 0.0006325244903564453
}

Which shows it is incorrectly parsing the series name and splitting it into a series and an episode name.

I am having the same issue with "Magnum P.I." (2018) and "Magnum P.I" (1980), but this is perhaps more explicable.

**Comment by p0psicles** [comment]
I suspect this is fixed in the develop branch

**Comment by doodyd** [comment]
> I suspect this is fixed in the develop branch

Cool.  I searched the issues here but didn't find anything.  Is there an issue you can point me to?

**Comment by doodyd** [comment]
I have just realised that I don't seem to have the same issue with "FBI" and "FBI: Most Wanted", so it's not as straightforward as I first thought either.

**Comment by p0psicles** [comment]
You've posted your issue in the wrong project. Should be in https://github.com/pymedusa/Medusa

**Comment by doodyd** [comment]
![image](https://user-images.githubusercontent.com/29137584/167971804-4fc74550-42d5-475b-b03f-29bc73431f1f.png)
I don't think so.  This is the link as provided on the medusa configuration page.  If it's wrong, that's not on me.

**Comment by p0psicles** [comment]
That's where the source of Medusas website is hosted. It even warns you in it's README.md not to report issues there. But all's good

**Comment by doodyd** [comment]
OK… my mistake, but in truth I didn’t even get as far as the “source” link because a label of “website” doesn’t scream “this is the source code for the website”, it says “this is the medusa website.”  It doesn’t even matter what the link text is, because no one really looks, they (we) just click.

 

I’ve been a programmer for over 35 years, so if I can make this mistake, I am not going to be alone.

 

Can I therefore make a couple of suggestions:

 

1.	Add a direct link to the issues page.  Label it as “issues” or “bug reports”.  Something really obvious.  Every app should have a simple, clear mechanism for reporting bugs and not everyone will be familiar with github.
2.	Make the “issues”, “source” and “wiki” links the first 3 links in this section.  These 3 links are the ones 99.9% of your users will want.  Positioning them at the top is just good UX/UI.  I can’t imagine many users will be reporting issues with the website and only select users will bother with IRC.
3.	Finally, perhaps “website source” is a clearer label for the link I (incorrectly) used.

 

Anyway, my 2 cents.  Do or do not as you see fit.

 

 

PS: I did find an exact replication of my bug on the site once I was on the correct project.  That led me to a solution (using scene exceptions) that I *think* is working.  I won’t know for sure until the next episode is released.

 

Thanks for your replies.

**Comment by p0psicles** [comment]
If you want to test out your scene exception against a possible release name. You can use the guessit tool on the page postprocessing - guessit tab. If it can match the release against a title it will show you a link.
