### ISSUE TITLE
Alias 321670

### ISSUE THREAD

**Issue by IDerr** [pymedusa/medusa.github.io#46]
Is It Wrong to Try to Pick Up Girls in a Dungeon? On the Side: Sword Oratoria

Add this alias 👍 
https://www.nyaa.se/?page=search&cats=0_0&filter=0&term=%3A+DanMachi+Gaiden+-+Sword+Oratoria

DanMachi Gaiden - Sword Oratoria

**Comment by medariox** [comment]
What's the issue?

**Comment by IDerr** [comment]
Was juste to keep a track
