### ISSUE TITLE
Search Providers Custom setting causing problems

### ISSUE THREAD

**Issue by Bangorbob** [pymedusa/medusa.github.io#461]
Serveral of my search providers are now not working properly, showing no results on the test button, Lime torrents, TGx:Home, HDSpace and HDBits all worked before without any problems. HDBits now also causes a password reset on there site, I have also changed the passkey several times but no joy.

[log.txt](https://github.com/pymedusa/medusa.github.io/files/11990691/log.txt)

![image](https://github.com/pymedusa/medusa.github.io/assets/650513/7d0f1ea9-54b7-4d41-8c33-5635cf02b3d6)

**Comment by medariox** [comment]
No changes in the code since years. Please open issues here: https://github.com/pymedusa/Medusa/issues
