### ISSUE TITLE
Mobile "show list" view has no episode thumbnails and tapping on them only scales the image up

### ISSUE THREAD

**Issue by loki495** [pymedusa/medusa.github.io#53]
Check attached screenshot from my iPhone 6. No thumbnails, and can't get into the show details. I've been getting into particular pages from the "recent shows" list and changing the show from the drop down menu. Didn't have the issue with the original SickRage.

![img_0175](https://cloud.githubusercontent.com/assets/20133903/26032237/7b79cd1a-3843-11e7-80f1-aae8804fdb7f.PNG)

**Comment by p0psicles** [comment]
Which browser are u using?

**Comment by loki495** [comment]
Safari on iOS 10.2

**Comment by medariox** [comment]
Do you have a JavaScript/Ad blocker installed? Does it work with Chrome on iOS? Sadly I can't check this myself as I don't have an iPhone.

**Comment by medariox** [comment]
If you still have this issue, please open a new issue here: https://github.com/pymedusa/Medusa/issues
